name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build containers
        run: docker-compose build

    - name: Run containers
        run: docker-compose up -d

    - name: Test backend
        run: curl --fail http://localhost:5000/api/data || exit 1

    - name: Test frontend
        run: curl --fail http://localhost:8081 || exit 1

